### PR TITLE
feat: 🎸 remove recent bill

### PR DESCRIPTION
**Pull request by K1ethoang**

### CODE REVIEW

**Review by Balastrong — CHANGES_REQUESTED** [review]
The code looks good!

Just one thing, I see an check is failing because the files are not formatted. Can you please format them? Either manually or with `npm run format`

Thank you!

**Comment by K1ethoang** [comment]
> The code looks good!
> 
> 
> 
> Just one thing, I see an check is failing because the files are not formatted. Can you please format them? Either manually or with `npm run format`
> 
> 
> 
> Thank you!

Wheb I run that command, about 50 files are changed and ready to add 50 files to push?

**Comment by Balastrong** [comment]
50 files are definitely too many, can you format for now only the two that you modified?

**Review by Balastrong — APPROVED** [review]
LGTM, thank you!

**Comment by Balastrong** [comment]
@all-contributors please add @K1ethoang for code

**Pull request merged**
