### PR TITLE
chore: set default value on start page

### PR DESCRIPTION
**Pull request by K1ethoang**

### CODE REVIEW

**Comment by Balastrong** [comment]
Thanks for the PR!

This indeed works, but the idea is that the user should be able to decide a name and a number from the homepage, and from there pass the parameters to the new bill.

**Comment by K1ethoang** [comment]
Okay, I will see it and remake

**Comment by K1ethoang** [comment]
image
image
---
@Balastrong Help me to review code 💯

**Review by Balastrong — APPROVED** [review]
Good idea using query params, LGTM! 🚀

**Pull request merged**
